version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
services:
  db:
    image: mysql
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
    - back
  app:
    image: piwik:fpm
    links:
      - db
    volumes:
      - ./piwik-config:/var/www/html/config
      - ./fpm-config/php-fpm.d-extra:/usr/local/etc/php-fpm.d-extra
      - ./fpm-config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
    - back
  web:
    image: nginx
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
      - lb_web
    #uncomment these if you don't plan to add a proxy in front of nginx or can be used for debugging
    #ports:
    #  - "80:80"
    #  - "443:443"
  cron:
    image: piwik:fpm
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
    - back
